version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - run: echo "checkout and unit tests"
  deploy_backend:
    machine: true
    steps:
      - run: echo "deploy backend"
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "integration tests backend"
  deploy_staging:
    machine: true
    steps:
      - run: echo "deploy staging"
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "acceptance tests 1"
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "acceptance tests 2"
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "acceptance tests 3"
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "acceptance tests 4"                  
  deploy_production:
    machine: true
    steps:
      - run: echo "deploy production"
workflows:
  build:
    jobs:
      - checkout_and_unit_test
      - deploy_backend:
          requires:
            - checkout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging                                    
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
